# Generated by Django 4.0.5 on 2022-06-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('code', models.CharField(default=True, max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('technologies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Project.technologies')),
                ('version', models.CharField(max_length=20)),
            ],
            bases=('Project.technologies',),
        ),
        migrations.CreateModel(
            name='Operating_System',
            fields=[
                ('technologies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Project.technologies')),
            ],
            bases=('Project.technologies',),
        ),
        migrations.CreateModel(
            name='Programming_Language',
            fields=[
                ('technologies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Project.technologies')),
                ('image', models.ImageField(default=None, upload_to='images/')),
            ],
            bases=('Project.technologies',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('technologies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Project.technologies')),
            ],
            bases=('Project.technologies',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('github_Link', models.URLField(default=None)),
                ('frameworks', models.ManyToManyField(blank=True, to='Project.framework')),
                ('languages', models.ManyToManyField(to='Project.programming_language')),
                ('o_Systems', models.ManyToManyField(to='Project.operating_system')),
                ('tools', models.ManyToManyField(blank=True, to='Project.tool')),
            ],
        ),
    ]
