# Generated by Django 4.0.5 on 2022-06-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='frameworks',
            field=models.ManyToManyField(blank=True, to='Project.framework'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_Link',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(to='Project.programming_language'),
        ),
        migrations.AddField(
            model_name='project',
            name='o_Systems',
            field=models.ManyToManyField(to='Project.operating_system'),
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(blank=True, to='Project.tool'),
        ),
    ]
