# Generated by Django 4.1 on 2022-09-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='o_Systems',
        ),
        migrations.AlterField(
            model_name='technologies',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images/languages/'),
        ),
        migrations.DeleteModel(
            name='Operating_System',
        ),
    ]
