# Generated by Django 4.0.5 on 2022-06-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_project_frameworks_project_github_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='programming_language',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
