# Generated by Django 4.1 on 2022-09-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_remove_project_o_systems_alter_technologies_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_images',
            name='id',
        ),
        migrations.AlterField(
            model_name='project_images',
            name='imgCode',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
