# Generated by Django 4.1 on 2022-09-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_remove_project_images_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_Image',
            field=models.ImageField(default=None, null=True, upload_to='images/languages/'),
        ),
    ]
