# Generated by Django 4.0.5 on 2022-06-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('institution', models.CharField(max_length=60)),
                ('file', models.FileField(blank=True, upload_to='docs/degrees')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('idCode', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('description', models.TextField()),
                ('skills', models.JSONField()),
                ('github_Account', models.URLField()),
                ('linkedin_Profile', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('degree_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Owner.degree')),
                ('cert_Link', models.URLField(blank=True)),
            ],
            bases=('Owner.degree',),
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('position', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('start_Date', models.DateField()),
                ('quit_Date', models.DateField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.owner')),
            ],
        ),
        migrations.AddField(
            model_name='degree',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.owner'),
        ),
    ]
