# Generated by Django 4.0.5 on 2022-06-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('userName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('passwd', models.BinaryField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
