# Generated by Django 4.0.5 on 2022-06-11 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='passwd',
            new_name='password',
        ),
    ]
