# Generated by Django 4.0.5 on 2022-06-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_rename_passwd_owner_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
