# Generated by Django 4.0.5 on 2022-06-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_alter_owner_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='skills',
            field=models.JSONField(default=None),
        ),
    ]
